import os
from datetime import datetime
from telegram import Bot
import yfinance as yf
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Config from secrets
BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
GROUP_ID = os.getenv('TELEGRAM_GROUP_ID', '-5153249366')

if not BOT_TOKEN:
    logger.error("TELEGRAM_BOT_TOKEN not set")
    exit(1)

bot = Bot(token=BOT_TOKEN)

def get_stock(symbol):
    try:
        ticker = yf.Ticker(symbol)
        data = ticker.history(period="1d")
        if len(data) > 0:
            latest = data.iloc[-1]
            prev = ticker.info.get('previousClose', latest['Close'])
            change = ((latest['Close'] - prev) / prev) * 100 if prev else 0
            return {'price': round(latest['Close'], 2), 'change': round(change, 2)}
    except Exception as e:
        logger.error(f"Error {symbol}: {e}")
    return None

def generate_report():
    lines = [
        "📊 Hugo Sammie Family Office",
        f"🕐 {datetime.now().strftime('%Y-%m-%d %H:%M')} HK Time",
        ""
    ]
    
    # US Futures
    lines.append("🇺🇸 US Futures")
    futures = {'SPY': 'S&P 500', 'QQQ': 'Nasdaq', 'DIA': 'Dow'}
    for sym, name in futures.items():
        d = get_stock(sym)
        if d:
            e = "📈" if d['change'] > 0 else "📉"
            lines.append(f"{e} {name}: {d['change']:+.2f}%")
    
    # US Holdings
    lines.append("")
    lines.append("📈 US Holdings")
    for s in ['TSLA', 'AAPL', 'NVDA']:
        d = get_stock(s)
        if d:
            e = "🟢" if d['change'] > 0 else "🔴"
            lines.append(f"{e} {s}: ${d['price']} ({d['change']:+.2f}%)")
    
    # HK Holdings
    lines.append("")
    lines.append("📈 HK Holdings")
    names = {"0700.HK": "腾讯", "3690.HK": "美团", "1810.HK": "小米"}
    for s in ['0700.HK', '3690.HK', '1810.HK']:
        d = get_stock(s)
        if d:
            e = "🟢" if d['change'] > 0 else "🔴"
            lines.append(f"{e} {names.get(s, s)}: ${d['price']} ({d['change']:+.2f}%)")
    
    lines.append("")
    lines.append("💡 Auto-generated by Hugo Family Office AI")
    return "\n".join(lines)

def main():
    report = generate_report()
    logger.info(f"Report:\n{report}")
    
    try:
        bot.send_message(chat_id=CHAT_ID, text=report, parse_mode='HTML')
        logger.info(f"Sent to {CHAT_ID}")
        
        if GROUP_ID:
            bot.send_message(chat_id=GROUP_ID, text=report, parse_mode='HTML')
            logger.info(f"Sent to group {GROUP_ID}")
        
        logger.info("✅ Report sent successfully!")
    except Exception as e:
        logger.error(f"Failed to send: {e}")
        raise

if __name__ == '__main__':
    main()
